name: egote_services_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-15.0.dev <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  go_router: ^9.0.0
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  sentry_flutter: ^7.8.0
  shared_preferences: ^2.1.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  geoflutterfire2: 2.3.15
  connectycube_sdk: ^2.5.7
  connectivity_plus: ^4.0.1
  freezed_annotation: 2.2.0
  supabase_flutter: ^1.10.4
  fpdart: 0.6.0
  json_annotation: 4.8.1
  uni_links: 0.5.1
  uuid: ^3.0.7
  url_launcher: 6.1.11
  cloud_firestore: ^4.8.1
  sqflite: ^2.2.8+4
  flutter: 
    sdk: flutter
  path_provider: ^2.0.15
  comment_box: ^0.0.18
  settings_ui: ^2.0.2
  intl: ^0.18.1
  formz: ^0.6.0
  flutter_localization: ^0.1.12
  flutter_advanced_drawer: ^1.3.5
  lottie: ^2.4.0
  supabase_auth_ui: ^0.2.0
  flutter_svg: ^2.0.7
  flex_color_scheme: ^7.1.2
  flex_color_picker: ^3.2.2
  flutter_local_notifications: ^14.1.1
  firebase_messaging: ^14.6.4
  device_info_plus: ^9.0.2
  package_info_plus: ^4.0.2
  universal_io: ^2.2.2
  flutter_app_badger: ^1.5.0
  emoji_picker_flutter: ^1.6.1
  cached_network_image: ^3.2.3
  file_picker: ^5.3.2
  photo_view: ^0.14.0
  firebase_ui_auth: ^1.5.0

dev_dependencies: 
  flutter_lints: ^2.0.1
  riverpod_generator: ^2.2.3
  go_router_builder: ^2.1.1
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_lint: ^1.3.2
  custom_lint: ^0.4.0
  flutter_flavorizr: ^2.2.1
  flutter_test: 
    sdk: flutter
  flutter_gen_runner: ^5.3.1
  icons_launcher: ^2.1.2

flutter_gen:
  integrations:
    flutter_svg: true

flutter: 
  assets: 
    - assets/lottie/image/carrelage_background.jpg
    - assets/lottie/image/godzy_logo.png
    - assets/lottie/image/logo_bat_services.png
    - assets/lottie/image/digital-transformation-teaser.jpg
    - assets/lottie/image/digital_transf.jpg
    - assets/lottie/image/maison_indiv.png
    - assets/lottie/image/appartement.png
    - assets/lottie/image/triangle.png
    - assets/lottie/image/logo_tchat_1022x1024.png
    - assets/lottie/archive/amenagement/interrieur/sol/matiere/pvc/sol_pvc_holywell.png
    - assets/lottie/archive/amenagement/exterieur/piscines/piscine_sussargue_1.jpg
    - assets/lottie/models/AndroidLargeRobot.gif
    - assets/lottie/models/AndroidRobot.gif
    - assets/lottie/models/Arctic_Fox_Sitting.gif
    - assets/lottie/models/ArcticFox.gif
    - assets/lottie/models/TocoLargeToucan.gif
    - assets/lottie/models/TocoToucan.gif
    - assets/lottie/models/fox_face_mesh_texture.png
    - assets/lottie/models/foxface.gif
    - assets/lottie/models/frame.svg
    - assets/lottie/models/frame2.png
    - assets/lottie/models/prova_texture.png
    - assets/lottie/models/venom.jpg
    - assets/lottie/models/venom_with_eyes.jpg
    - assets/lottie/models/earth.jpg
    - assets/lottie/models/earth_2.jpg
    - assets/lottie/models/earth_augmented_image.jpg
    - assets/lottie/models/copertina.jpg
    - assets/lottie/models/umano_digitale.png
    - assets/lottie/models/myimages.imgdb
    - assets/lottie/models/topolino.jpg
    - assets/lottie/models/santa_maria_madalena/
    - assets/lottie/models/LottieLogo1.json
    - assets/lottie/models/
    - assets/lottie/
    - assets/json/
    - assets/json/development.config.json
    - assets/json/local.config.json
    - assets/json/production.config.json
    - assets/fonts/
  fonts: 
    - family: Pacifico
      fonts: 
        - asset: assets/fonts/Pacifico-Regular.ttf
          style: italic

  uses-material-design: true
  generate: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    local:
      app:
        name: "egote_services_v2 Local"

      android:
        applicationId: "com.godzy.egote_services_v2.local"
      ios:
        bundleId: "com.godzy.egote_services_v2.local"

    development:
      app:
        name: "egote_services_v2 Development"

      android:
        applicationId: "com.godzy.egote_services_v2.dev"
      ios:
        bundleId: "com.godzy.egote_services_v2.dev"

    production:
      app:
        name: "Example Production"

      android:
        applicationId: "com.godzy.egote_services_v2"
      ios:
        bundleId: "com.godzy.egote_services_v2"