name: egote_services_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.4.0

dependencies:
  cupertino_icons: ^1.0.8
  go_router: ^14.1.4
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sentry_flutter: ^8.2.0
  flutter_plugin_android_lifecycle: ^2.0.20
  shared_preferences: ^2.2.3
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_database: ^10.5.7
  geoflutterfire2: 2.3.15
  #  connectycube_sdk: ^2.11.4
  connectivity_plus: ^6.0.3
  freezed_annotation: ^2.4.1
  supabase_flutter:
    git:
      url: https://github.com/supabase/supabase-flutter.git
      ref: main
      path: packages/supabase_flutter

  fpdart: ^1.1.0
  json_annotation: ^4.9.0
  #  uni_links: 0.5.1
  uuid: ^4.4.0
  #  url_launcher: ^6.2.6
  cloud_firestore: ^4.17.5
  sqflite: ^2.3.3+1
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  comment_box: ^0.0.18
  settings_ui: ^2.0.2
  formz: ^0.7.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_advanced_drawer: ^1.3.6
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  flex_color_scheme: ^7.3.1
  flex_color_picker: '>=3.4.1 <4.0.0'
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^14.9.4
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  universal_io: ^2.2.2
  #  flutter_app_badger: ^1.5.0
  emoji_picker_flutter: ^2.2.0
  cached_network_image: ^3.3.1
  file_picker: ^8.0.3
  photo_view: ^0.15.0
  firebase_ui_auth: ^1.14.0
  datadog_flutter_plugin: ^2.5.0
  mocktail: ^1.0.3
  hive: ^2.2.3
  badges: ^3.1.2
  multi_link_text: ^0.0.5
  google_generative_ai: ^0.4.1
  #  url_launcher_android: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  riverpod_generator: '>=2.4.2 <3.0.0-dev.2'
  go_router_builder: ^2.7.0
  build_runner: ^2.4.10
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.12
  custom_lint: ^0.6.4
  flutter_flavorizr: ^2.2.3
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.5.0+1
  icons_launcher: ^2.1.7

dependency_overrides:
  meta: any

flutter_gen:
  output: lib/gen
  integrations:
    flutter_svg: true

flutter:
  assets:
    - assets/lottie/image/carrelage_background.jpg
    - assets/lottie/image/godzy_logo.png
    - assets/lottie/image/img_not_available.jpg
    - assets/lottie/image/logo_bat_services.png
    - assets/lottie/image/digital-transformation-teaser.jpg
    - assets/lottie/image/digital_transf.jpg
    - assets/lottie/image/maison_indiv.png
    - assets/lottie/image/appartement.png
    - assets/lottie/image/triangle.png
    - assets/lottie/image/logo_tchat_1022x1024.png
    - assets/lottie/archive/amenagement/interrieur/sol/matiere/pvc/sol_pvc_holywell.png
    - assets/lottie/archive/amenagement/exterieur/piscines/piscine_sussargue_1.jpg
    - assets/lottie/models/AndroidLargeRobot.gif
    - assets/lottie/models/AndroidRobot.gif
    - assets/lottie/models/Arctic_Fox_Sitting.gif
    - assets/lottie/models/ArcticFox.gif
    - assets/lottie/models/TocoLargeToucan.gif
    - assets/lottie/models/TocoToucan.gif
    - assets/lottie/models/fox_face_mesh_texture.png
    - assets/lottie/models/foxface.gif
    - assets/lottie/models/frame.svg
    - assets/lottie/models/frame2.png
    - assets/lottie/models/prova_texture.png
    - assets/lottie/models/venom.jpg
    - assets/lottie/models/venom_with_eyes.jpg
    - assets/lottie/models/earth.jpg
    - assets/lottie/models/earth_2.jpg
    - assets/lottie/models/earth_augmented_image.jpg
    - assets/lottie/models/copertina.jpg
    - assets/lottie/models/umano_digitale.png
    - assets/lottie/models/myimages.imgdb
    - assets/lottie/models/topolino.jpg
    - assets/lottie/models/santa_maria_madalena/
    - assets/lottie/models/LottieLogo1.json
    - assets/lottie/models/
    - assets/lottie/
    - assets/json/
    - assets/json/development.config.json
    - assets/json/local.config.json
    - assets/json/production.config.json
    - assets/fonts/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          style: italic

    - family: FlexIcons
      fonts:
        - asset: assets/fonts/FlexIcons.ttf

  uses-material-design: true
  generate: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    local:
      app:
        name: "egote_services_v2 Local"

      android:
        applicationId: "com.godzy.egote_services_v2.local"
      ios:
        bundleId: "com.godzy.egote_services_v2.local"

    development:
      app:
        name: "egote_services_v2 Development"

      android:
        applicationId: "com.godzy.egote_services_v2.dev"
      ios:
        bundleId: "com.godzy.egote_services_v2.dev"

    production:
      app:
        name: "Example Production"

      android:
        applicationId: "com.godzy.egote_services_v2"
      ios:
        bundleId: "com.godzy.egote_services_v2"