org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Duser.language=fr -Duser.country=FR -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
org.gradle.console=verbose
org.gradle.parallel=true
org.gradle.caching=true

# System properties
systemProp.pts.enabled=true
systemProp.log4j2.disableJmx=true
systemProp.file.encoding = UTF-8

# Project properties
kotlin.code.style=official
android.nonTransitiveRClass=false
spring-boot.version = 2.2.1.RELEASE