[versions]
firebaseBom = "33.9.0"
ktx = "1.15.0"
androidGradlePlugin = "8.1.4"
kotlinAndroidPlugin = "2.1.10"
protolayout = "1.2.1"
tiles = "1.4.1"

[libraries]
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-protolayout = { module = "androidx.wear.protolayout:protolayout", version.ref = "protolayout" }
androidx-tiles = { module = "androidx.wear.tiles:tiles", version.ref = "tiles" }
androidx-protolayout-expression = { module = "androidx.wear.protolayout:protolayout-expression", version.ref = "protolayout" }
androidx-protolayout-material = { module = "androidx.wear.protolayout:protolayout-material", version.ref = "protolayout" }
commons-httpclient = { module = "commons-httpclient:commons-httpclient" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }